allow-deps:
  - 'package.json'
  - 'package-lock.json'
  - 'pnpm-lock.yaml'
  - 'yarn.lock'
allow-config:
  - '.github/**'
  - 'next.config.*'
  - 'vite.config.*'
  - 'tsconfig*.json'
  - 'render.*'
  - 'Dockerfile'
  - 'docker/**'
