name: refresh
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  push:
    branches: [main]
permissions:
  contents: read
  pull-requests: write
jobs:
  bump:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      REPO: ${{ github.repository }}
    steps:
      - name: Update branches and set auto-merge
        run: |
          set -euo pipefail
          prs=$(gh pr list --repo "$REPO" --state open --json number --jq '.[].number')
          for i in $prs; do
            gh api -X PUT "repos/$REPO/pulls/$i/update-branch" >/dev/null 2>&1 || true
          done
          auto=$(gh pr list --repo "$REPO" --state open --search "label:automerge" --json number --jq '.[].number')
          for i in $auto; do
            gh pr merge "$i" --repo "$REPO" --auto --squash || true
          done
