name: agent-automerge
on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
permissions:
  contents: write
  pull-requests: write
  actions: read
  checks: read
jobs:
  enable:
    if: startsWith(github.event.pull_request.head.ref, 'agent-')
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: automerge
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          merge-method: merge
